<Project>
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <appdata Condition="'$(appdata)' == '' and '$(APPDATA)' != ''">$(APPDATA)</appdata>
    <AppData Condition="'$(AppData)' == '' and '$(APPDATA)' != ''">$(APPDATA)</AppData>

    <!-- Override SDK default (international) with CN path if it exists -->
    <DalamudLibPath Condition="Exists('$(APPDATA)\XIVLauncherCN\addon\Hooks\dev\')">$(APPDATA)\XIVLauncherCN\addon\Hooks\dev\</DalamudLibPath>
    <DalamudLibPath Condition="!Exists('$(APPDATA)\XIVLauncherCN\addon\Hooks\dev\') and Exists('$(APPDATA)\XIVLauncher\addon\Hooks\dev\')">$(APPDATA)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
  </PropertyGroup>
</Project>
